#!/bin/bash -l
#SBATCH -p serial
#SBATCH -J similarity
#SBATCH -o output-1599/log.txt
#SBATCH -e output-1599/err.txt
#SBATCH -t 00:30:00
#SBATCH -n 1
#SBATCH -N 1
#SBATCH -c 8
#SBATCH --mem=30000
#
./similarity-1599.sh
